language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
if: (type = push AND branch IN (master)) OR (type = pull_request)
before_install:
  - export PIP_USE_MIRRORS=true
  - pip install -U pip setuptools
  - pip install -U pytest  # https://github.com/travis-ci/travis-ci/issues/4873
  - pip install -U mock  # https://github.com/travis-ci/travis-ci/issues/4873
  - pip install coveralls
  - git config --global user.name 'travis-ci'
  - git config --global user.email 'travis@nowhere.edu'
install:
  - "pip install -e ."
script: coverage run --source=vcspull setup.py test
addons:
  apt:
    packages:
    - mercurial
    - git-core
    - subversion
    - cvs
after_success:
  - bash <(curl -s https://codecov.io/bash)
