language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install:
  - export PIP_USE_MIRRORS=true
  - pip install -U pip setuptools
  - pip install -U pytest  # https://github.com/travis-ci/travis-ci/issues/4873
  - pip install coveralls
  - git config --global user.name 'travis-ci'
  - git config --global user.email 'travis@nowhere.edu'
install:
  - "pip install -e ."
script: coverage run --source=vcspull setup.py test
addons:
  apt:
    packages:
    - mercurial
    - git-core
    - subversion
    - cvs
after_success:
  - coveralls
